# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mizahnyx's Blog
email: sjenkinsc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Game development, dissident game criticism, dissident game politics.
  The cultures are at war! Hold tightly your cat-person slave, pick up your weapons and FIGHT!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mizahnyx.github.com" # the base hostname & protocol for your site
twitter_username: mizanyx
github_username: mizahnyx

# Build settings
markdown: kramdown
theme: minima

# Defaults
defaults:
  - scope: 
      path: "assets/img"
    values:
      image: true 
